### PR TITLE
Replaced ternary with bitwise magic

### PR DESCRIPTION
**Pull request by GHXX**
The submitted change, as proposed by @00asdf should be a bit faster :)

### CODE REVIEW

**Comment by JimmyCushnie** [comment]
bruh this doesn't even compile. Cannot implicitly convert type 'ulong' to 'int'

**Comment by GHXX** [comment]
:(

**Comment by JimmyCushnie** [comment]
Also it doesn't actually work lol, here's the output from running the (fixed) code 10 times

```
18446744073709551615
18446744073709551615
18446744073709551615
1
18446744073709551615
18446744073709551615
18446744073709551615
1
18446744073709551615
18446744073709551615
```

**Comment by JimmyCushnie** [comment]
Superseded by 6afeed6

**Pull request closed without merging**
